import { AbilityConstant, ConfigurationConstant, UIAbility, Want } from '@kit.AbilityKit';
import { hilog } from '@kit.PerformanceAnalysisKit';
import { window } from '@kit.ArkUI';
import { ContextUtil } from '../utils/context/ContextUtil';
import { WindowUtil } from '../utils/window/WindowUtil';
import { kAppStatus } from '../status/AppStatus';
import { kUserStatus } from '../status/UserStatus';
import { LogUtil } from '../utils/log/LogUtil';

const DOMAIN = 0x0000;

export default class EntryAbility extends UIAbility {
  onCreate(want: Want, launchParam: AbilityConstant.LaunchParam): void {
    try {
      ContextUtil.init(this.context)
      kAppStatus.isLaunch = true
      this.context.getApplicationContext().setColorMode(ConfigurationConstant.ColorMode.COLOR_MODE_NOT_SET);
    } catch (err) {
      hilog.error(DOMAIN, 'testTag', 'Failed to set colorMode. Cause: %{public}s', JSON.stringify(err));
    }
    hilog.info(DOMAIN, 'testTag', '%{public}s', 'Ability onCreate');
  }

  onDestroy(): void {
    hilog.info(DOMAIN, 'testTag', '%{public}s', 'Ability onDestroy');
  }

  onWindowStageCreate(windowStage: window.WindowStage): void {
    // Main window is created, set main page for this ability
    hilog.info(DOMAIN, 'testTag', '%{public}s', 'Ability onWindowStageCreate');

    WindowUtil.init(windowStage)

    windowStage.loadContent('pages/Index', (err) => {
      if (err.code) {
        hilog.error(DOMAIN, 'testTag', 'Failed to load the content. Cause: %{public}s', JSON.stringify(err));
        return;
      }

      try {
        ContextUtil.setUIContext(windowStage.getMainWindowSync().getUIContext())
      } catch (err) {
        hilog.error(DOMAIN, 'testTag', 'Failed to load the Window or UIContext. Cause: %{public}s',
          JSON.stringify(err));
      }
      hilog.info(DOMAIN, 'testTag', 'Succeeded in loading the content.');
    });
  }

  onWindowStageDestroy(): void {
    // Main window is destroyed, release UI related resources
    hilog.info(DOMAIN, 'testTag', '%{public}s', 'Ability onWindowStageDestroy');
    ContextUtil.removeUIContext()
  }

  onForeground(): void {
    // Ability has brought to foreground
    hilog.info(DOMAIN, 'testTag', '%{public}s', 'Ability onForeground');
    if (!kAppStatus.isLaunch) {
      kAppStatus.hotLaunch = true
      LogUtil.info('AppStatus', '热启动')
    } else {
      LogUtil.info('AppStatus', '冷启动')
    }
  }

  onBackground(): void {
    // Ability has back to background
    hilog.info(DOMAIN, 'testTag', '%{public}s', 'Ability onBackground');
    kAppStatus.isLaunch = false
  }
}